src/Entity/ContactFormMessage.php
<?php

declare(strict_types=1);

namespace MangoSylius\SyliusContactFormPlugin\Entity;

use Doctrine\ORM\Mapping as ORM;
use Sylius\Component\Core\Model\CustomerInterface;
use Sylius\Component\Resource\Model\ResourceInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="mangoweb_contact_form")
 */
class ContactFormMessage implements ResourceInterface, ContactFormMessageInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @var string|null
     */
    protected $customerName;

    /**
     * @ORM\Column(type="string", nullable=false)
     *
     * @var string|null
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    protected $email;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     *
     * @var string|null
     */
    protected $phone;

    /**
     * @var string|null
     *
     * @ORM\Column(type="text", nullable=false)
     * @Assert\NotBlank()
     */
    protected $message;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="datetime")
     */
    protected $createdAt;

    /**
     * @var CustomerInterface|null
     *
     * @ORM\ManyToOne(targetEntity="Sylius\Component\Customer\Model\CustomerInterface")
     */
    protected $customer;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $userAgent;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $ip;

    public function getCustomerDescriptor(): ?string
    {
        return $this->customerName ?? $this->email;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function setId(int $id): void
    {
        $this->id = $id;
    }

    public function getCustomerName(): ?string
    {
        return $this->customerName;
    }

    public function setCustomerName(?string $customerName): void
    {
        $this->customerName = $customerName;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): void
    {
        $this->phone = $phone;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): void
    {
        $this->message = $message;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    public function getCustomer(): ?CustomerInterface
    {
        return $this->customer;
    }

    public function setCustomer(?CustomerInterface $customer): void
    {
        $this->customer = $customer;
    }

    public function getUserAgent(): ?string
    {
        return $this->userAgent;
    }

    public function setUserAgent(?string $userAgent): void
    {
        $this->userAgent = $userAgent;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(?string $ip): void
    {
        $this->ip = $ip;
    }
}

src/Resources/views/Admin/show.html.twig
{% extends '@SyliusAdmin/layout.html.twig' %}

{% import '@SyliusAdmin/Macro/breadcrumb.html.twig' as breadcrumb %}

{% block title %}{{ 'mango_contact_form_plugin.ui.detailTitle'|trans ({'%customerName%': message.customerDescriptor }) }}{% endblock %}

{% block content %}

    <div class="ui stackable one column grid">
        <div class="column">
            <h1 class="ui header">
                <i class="circular comments icon"></i>
                <div class="content">
                    {{ 'mango_contact_form_plugin.ui.title'|trans }}
                    <div class="sub header">{{ 'mango_contact_form_plugin.ui.subtitle'|trans }}</div>
                </div>
            </h1>

            {% set breadcrumbs = [
                { label: 'sylius.ui.administration'|trans, url: path('sylius_admin_dashboard') },
                { label: 'mango_contact_form_plugin.ui.title'|trans, url: path('mango_contact_form_plugin_admin_message_index') },
                { label: message.customerDescriptor },
            ] %}

            {{ breadcrumb.crumble(breadcrumbs) }}
        </div>

        <div class="column">
            <div class="ui threaded comments segment">
                <div class="comment">
                    <div class="content">
                        <span class="author">
                            {{ 'mango_contact_form_plugin.admin.show.custommer'|trans }}:
                            <br>
                            {{ message.customerDescriptor }}
                        </span>
                        <div class="metadata">
                            <span class="date">{{ 'mango_contact_form_plugin.time'|trans ({'%time%': message.createdAt|date('Y-m-d H:i:s') }) }}</span>
                        </div>
                        <div class="text">
                            {{ message.message }}
                        </div>
                    </div>
                </div>

                {% if answers %}
                    {% for answer in answers %}
                        <div class="comment messageAnswer">
                            <div class="content">
                                <span class="author">
                                    {% if answer.adminUser %}
                                        {{ 'mango_contact_form_plugin.admin.show.admin'|trans }}:
                                        <br>
                                        {{ answer.adminUser.username }}
                                    {% else %}
                                        {{ 'mango_contact_form_plugin.admin.show.custommer'|trans }}:
                                        <br>
                                        {{ message.customerDescriptor }}
                                    {% endif %}
                                </span>
                                <div class="metadata">
                                    <span class="date">{{ 'mango_contact_form_plugin.time'|trans ({'%time%': answer.createdAt|date('Y-m-d H:i:s') }) }}</span>
                                </div>
                                <div class="text">
                                    {{ answer.message }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}

                <h4 class="ui dividing header">{{ 'mango_contact_form_plugin.title.answer'|trans }}</h4>
                <div class="ui form">
                    {{ form_start(form, {'attr': {'class': 'ui reply form'}}) }}
                    <div class="field">
                        {{ form_row(form.message) }}
                    </div>
                    <button type="submit" class="ui blue labeled submit icon button" id="formSubmitButton">
                        <i class="icon edit"></i> {{ 'mango_contact_form_plugin.admin.form.submitButton'|trans }}
                    </button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>


{% endblock %}